version: "3.1"

services:
  db:
    container_name: dev_db
    image: postgres:12
    restart: always
    volumes:
      - ../pgdb/:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    env_file: ../.env
